--------------------------------------------------------
--  Fichier créé - vendredi-novembre-15-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "HOUSSEM"."CLIENT" 
   (	"CLIENT_ID" NVARCHAR2(20), 
	"NAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(20 BYTE), 
	"DATEN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HOUSSEM.CLIENT
SET DEFINE OFF;
Insert into HOUSSEM.CLIENT (CLIENT_ID,NAME,EMAIL,TEL,SEXE,DATEN) values ('36985214','dd','saz@gmail.com','74125896','M',to_date('01/01/00','DD/MM/RR'));
Insert into HOUSSEM.CLIENT (CLIENT_ID,NAME,EMAIL,TEL,SEXE,DATEN) values ('12120022','aaaaa','d.@gmail.com','85236974','M',to_date('01/01/99','DD/MM/RR'));
Insert into HOUSSEM.CLIENT (CLIENT_ID,NAME,EMAIL,TEL,SEXE,DATEN) values ('41002630','xxx','xx@esprit.tn','14785236','F',to_date('01/01/00','DD/MM/RR'));
Insert into HOUSSEM.CLIENT (CLIENT_ID,NAME,EMAIL,TEL,SEXE,DATEN) values ('00002365','cd','cx@esprit.tn','75315963','M',to_date('15/11/02','DD/MM/RR'));
Insert into HOUSSEM.CLIENT (CLIENT_ID,NAME,EMAIL,TEL,SEXE,DATEN) values ('96325802','aaaaa','d@gmail.com','41002630','F',to_date('01/01/00','DD/MM/RR'));
Insert into HOUSSEM.CLIENT (CLIENT_ID,NAME,EMAIL,TEL,SEXE,DATEN) values ('02155555','cxesprittn','x@esprit.tn','02155555','F',to_date('01/01/00','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index SYS_C007130
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOUSSEM"."SYS_C007130" ON "HOUSSEM"."CLIENT" ("CLIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007131
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOUSSEM"."SYS_C007131" ON "HOUSSEM"."CLIENT" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "HOUSSEM"."CLIENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HOUSSEM"."CLIENT" ADD PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOUSSEM"."CLIENT" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
